import { useState } from 'react'
import Icon from '../../components/Icon'
const statusOptions = ['Saved', 'Applied', 'Interview', 'Offer', 'Rejected']
const types = ['Working student', 'Part time', 'Full time', 'Internship', 'Freelance', 'Other']
const blank = { company: '', role: '', type: 'Working student', status: 'Applied', location: '', link: '', notes: '' }
export default function ApplicationsPage({ store }) {
  const [form, setForm] = useState(blank); const [editing, setEditing] = useState(null); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All')
  const items = store.applications.filter((item) => (filter === 'All' || item.status === filter) && `${item.company} ${item.role}`.toLowerCase().includes(query.toLowerCase()))
  function submit(event) {
    event.preventDefault()
    if (editing) store.updateApplication(editing, form)
    else store.addApplication(form)
    setForm(blank)
    setEditing(null)
  }
  function beginEdit(item) { setEditing(item.id); setForm(item); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  return <div className="page feature-page"><PageTitle kicker="JOB SEARCH" title="Applications" text="Track every opportunity, from a saved role to an offer." action="Add application" onClick={() => document.querySelector('#application-form').scrollIntoView({ behavior: 'smooth' })}/>
    <section className="panel form-panel" id="application-form"><div><p className="section-kicker">{editing ? 'EDIT APPLICATION' : 'NEW APPLICATION'}</p><h2>{editing ? 'Update opportunity' : 'Add an opportunity'}</h2></div><form className="entry-form" onSubmit={submit}><label>Company<input value={form.company} onChange={(e) => setForm({ ...form, company: e.target.value })} required placeholder="e.g. Siemens"/></label><label>Role<input value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} required placeholder="e.g. Software Developer"/></label><div className="form-grid"><label>Role type<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}>{types.map((type) => <option key={type}>{type}</option>)}</select></label><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>{statusOptions.map((status) => <option key={status}>{status}</option>)}</select></label></div><div className="form-grid"><label>Location<input value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} placeholder="e.g. Berlin / Remote"/></label><label>Application link<input type="url" value={form.link} onChange={(e) => setForm({ ...form, link: e.target.value })} placeholder="https://..."/></label></div><label>Notes<textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} placeholder="Interview date, contact person, next step…"/></label><div className="form-actions">{editing && <button type="button" className="soft-button" onClick={() => { setForm(blank); setEditing(null) }}>Cancel</button>}<button className="primary-action">{editing ? 'Save changes' : 'Save application'} <Icon name="arrow" size={16}/></button></div></form></section>
    <section className="panel table-panel"><div className="list-toolbar"><div><p className="section-kicker">YOUR PIPELINE</p><h2>{store.applications.length} applications</h2></div><div className="filter-controls"><label className="search"><Icon name="search" size={15}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search"/></label><select value={filter} onChange={(e) => setFilter(e.target.value)}><option>All</option>{statusOptions.map((status) => <option key={status}>{status}</option>)}</select></div></div>{items.length ? <div className="application-table">{items.map((item) => <article className="application-card" key={item.id}><span className="company-logo">{item.company[0]}</span><div><strong>{item.company}</strong><p>{item.role} · {item.type}</p>{item.location && <small>{item.location}</small>}</div><span className={`pill ${item.status.toLowerCase()}`}>{item.status}</span><div className="row-actions"><button onClick={() => beginEdit(item)} title="Edit"><Icon name="edit" size={16}/></button><button onClick={() => store.removeApplication(item.id)} title="Delete"><Icon name="trash" size={16}/></button></div></article>)}</div> : <div className="empty-state full"><span><Icon name="briefcase"/></span><h3>No applications match this view</h3><p>Your tracked opportunities will appear here.</p></div>}</section>
  </div>
}
function PageTitle({ kicker, title, text, action, onClick }) { return <section className="page-title"><div><p className="eyebrow">{kicker}</p><h1>{title}</h1><p className="subtle">{text}</p></div><button className="top-add" onClick={onClick}><Icon name="plus" size={16}/>{action}</button></section> }
